### ISSUE TITLE
sscollector.pyz - file missing...as it is mentioned in gitignore file

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/Stormspotter#17]
sscollector.pyz - file missing...as it is mentioned in gitignore file

Instruction says -

cd stormcollector
python3 sscollector.pyz -h

**Comment by legra-ms** [comment]
If you're not using the Docker installation, then you need to grab the releases from [https://github.com/Azure/Stormspotter/releases](https://github.com/Azure/Stormspotter/releases) . 

The reason sscollector.pyz is in the gitignore is because I'm developing on Windows, and there are some dependencies that are Windows specific that won't work on Nix or probably MacOS. So the collector and backend pyz files are built using Github Actions so that you can grab the correct one for your OS.
