### ISSUE TITLE
missing rbac.json file inside results.zip

### ISSUE THREAD

**Issue by zur250** [Azure/Stormspotter#2]
Hi,
I am running the following command:
stormstopper --cli while being connected to global administrator account and this user also owner of the subscriptions in the account.
After quering all the API`s the results.zip is missing rbac.json file which causes stormdash script to crash

**Comment by mstair** [comment]
Not sure if specifically related, but when I execute stormstopper with `--azure-only` I get following error:

```
...
File "/home/user/.local/share/virtualenvs/Stormspotter-Kfk3px2p/lib/python3.8/site-packages/stormspotter/ingestor/assets/azure/rbac.py", line 82, in _get_permissions
    role_type = roles_json["properties"]["roleName"]
KeyError: 'properties'
```
I checked the roles_json API response and found:

```
{'error': {'code': 'AuthenticationFailed', 'message': "Authentication failed. The 'Authorization' header is missing."}}
```

If I add the Authorization header referencing the access_token from the ServicePrincipalCredentials object, it completes and produces a results.zip that includes rbac. Stormdash will process and produce a graph (I had to change/fix the input/results.zip -> processed move also).

I can submit a PR for these unless I am just executing stormstopper improperly.

**Comment by legra-ms** [comment]
I haven't been able to reproduce what @zur250 is going through but my test tenant is pretty limited. It shouldn't be crashing the dash, since there's a check to see if it rbac.json exists before trying to process it. Can you 

I do see a potential problem that might be causing the issue for @mstair but I haven't come across that issue either when using `--azure-only`  and a Service Principal. But Zur also sent me a screenshot of a service principal failing so I will revisit.

The whole authentication process needs to be written for clarity and with additional methods added (access token, MSI, etc). This is definitely one of the higher priorities and might end up fixing that issue.

**Comment by legra-ms** [comment]
Alright, y'all. I was having a moment....I wrote the docs wrong.

`get_spn_credentials` also requires the tenant ID to be passed on the command line. Updating the README to reflect this. Let me know if it works.
