### ISSUE TITLE
Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/Stormspotter#31]
Import of the result is done successfully but while running the query I am getting 'Cannot read property 'charAt' of undefined'...Please advise....

**Comment by legra-ms** [comment]
Can you provide more details please? i.e. The query, any additional errors in the browser console, etc.

**Comment by mdaslamansari** [comment]
With every query...for example -

MATCH (a:AADRole)<-[r:MemberOf]-(t) WHERE a.name = 'Company Administrator' RETURN *

**Comment by legra-ms** [comment]
There is an ingestion error there that's breaking your requests and is either hanging your neo4j session or just breaking it completely. Also, it looks like this might also happen if you try to query while the file is still ingesting. 

I would imagine that after the NeoClientError in the picture you provided, there is a cypher query or Azure/AAD object that was given back to you in the line right after. Can you provide that cypher query output? I would need more information about where that hyphen is that's breaking your queries in order to troubleshoot further. 

_**There may be sensitive data in the cypher query. Please blur anything that shouldn't be exposed.**_

**Comment by mdaslamansari** [comment]
Ok...

One Example -

stormspotter-backend_1   | "    MERGE (from)-[obj:ddd-Role_ABCNonACT_Storage-Contributor]->(to) SET obj.actions = ['Microsoft.Authorization/*/read', 'Microsoft.Insights/alertRules/*', 'Microsoft.Insights/diagnosticSettings/*', 'Microsoft.ResourceHealth/availabilityStatuses/read', 'Microsoft.Resources/deployments/*', 'Microsoft.Resources/subscriptions/resourceGroups/read', 'Microsoft.Storage/storageAccounts/*', 'Microsoft.Support/*', '*/read'], obj.not_actions = '[]', obj.data_actions = '[]', obj.not_data_actions = '[]', obj.roleName = 'ddd-Role_ABCNonACT_Storage-Contributor', obj.roleType = 'CustomRole', obj.roleDescription = 'abc STORAGE CONTRIBUTOR Role'"

**Comment by mdaslamansari** [comment]
It is working fine...May be it was taking time to import the data.
